### Imports

In [2]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib widget
from matplotlib import cm
from TLLnet import TLLnet
import importlib

In [2]:
importlib.reload(TLLnet)

<module 'TLLnet.TLLnet' from '/Users/james/Dropbox/Research/Postdoc Yasser/code/TLLnet/TLLnet.py'>

## A Manually Contructed, Non-Trivial SISO TLL Network

In [3]:
kern = np.ones(7)
bias = np.ones(7)
# l_1
m = (1.2-3.0)/(0.17+1)
kern[0] = m
bias[0] = m*(-0.17)+1.2
# l_2
m = (4.1-1.2)/(0.78-0.17)
kern[1] = m
bias[1] = m*(-0.17)+1.2
# l_3
m = (0.3-4.1)/(2-0.78)
kern[2] = m
bias[2] = m*(-0.78)+4.1
# l_4
m = (1.7-0.3)/(2.07-2)
kern[3] = m
bias[3] = m*(-2)+0.3
# l_5
m = (1.62-1.7)/(2.13-2.07)
kern[4] = m
bias[4] = m*(-2.07)+1.7
# l_6
m = (8.0-1.62)/(5-2.13)
kern[5] = m
bias[5] = m*(-2.13)+1.62
# l_7
m = (0-8.0)/(7.2-5)
kern[6] = m
bias[6] = m*(-5)+8.0

kern = np.array([kern])

e = np.eye(7)
selectorMats = [[] for k in range(8)]
selectorMats[0] = np.vstack([ e[:,0], e[:,2], e[:,4], e[:,6], e[:,6], e[:,6], e[:,6] ]).T
selectorMats[1] = np.vstack([ e[:,1], e[:,2], e[:,4], e[:,6], e[:,6], e[:,6], e[:,6] ]).T
selectorMats[2] = np.vstack([ e[:,1], e[:,2], e[:,6], e[:,6], e[:,6], e[:,6], e[:,6] ]).T
selectorMats[3] = np.vstack([ e[:,1], e[:,2], e[:,4], e[:,5], e[:,6], e[:,6], e[:,6] ]).T
selectorMats[4] = np.vstack([ e[:,1], e[:,3], e[:,4], e[:,5], e[:,6], e[:,6], e[:,6] ]).T
selectorMats[5] = np.vstack([ e[:,1], e[:,3], e[:,4], e[:,6], e[:,6], e[:,6], e[:,6] ]).T
selectorMats[6] = np.vstack([ e[:,1], e[:,3], e[:,5], e[:,6], e[:,6], e[:,6], e[:,6] ]).T
selectorMats[7] = np.vstack([ e[:,1], e[:,3], e[:,6], e[:,6], e[:,6], e[:,6], e[:,6] ]).T

In [4]:
mynet = TLLnet.TLLnet(linear_fns=7,uo_regions=8,flat=True,incBias=False)
mynet.setLocalLinFns(kern,bias)
for k in range(7):
    mynet.setSelector(selectorMats[k],k)

Metal device set to: AMD Radeon Pro 460


2021-11-03 13:13:19.709023: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-03 13:13:19.710176: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-11-03 13:13:19.711142: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [5]:
x = np.linspace(0,15,1000)
fig = plt.figure(7)
fig.clf()
y = mynet.model.predict(x.reshape((len(x),1)))
plt.plot(x,y)
plt.axis([0,3,0,6])
plt.grid()
plt.show()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

2021-11-03 13:13:27.273931: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-11-03 13:13:27.431695: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [56]:
x = np.linspace(0,15,1000)
fig = plt.figure(18)
fig.clf()
# y = kern[0][3]*x + bias[3]
# plt.plot(x,y)
# y = kern[0][4]*x + bias[4]
# plt.plot(x,y)
# y = kern[0][5]*x + bias[5]
# plt.plot(x,y)
# y = kern[0][5]*x + bias[5]
# plt.plot(x,y)
# y = kern[0][6]*x + bias[6]
# plt.plot(x,y)
# y = kern[0][3]*x + bias[3]
# plt.plot(x,y)
# y = mynet.model.predict(x.reshape((len(x),1)))
# plt.plot(x,y)
plt.axis([1,3,-10,10])
plt.grid()
plt.show()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [18]:
kern[0][1]-kern[0][6]

8.390461997019374

In [14]:
bias[6]

26.18181818181818

In [186]:
x = np.linspace(0,4,1000)
y1 = kern[0][1]*x + bias[1]
y3 = kern[0][3]*x + bias[3]
y6 = kern[0][6]*x + bias[6]
fig = plt.figure(17)
fig.clf()
plt.plot(x,y1, x,y3, x,y6 )
plt.grid()
plt.show()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

This is purely to help with the calculation of the selector sets. It computes all of the intersections of local linear functions, and indicates the order of *all* local linear functions at those intersections (as well as the pair of local linear functions that switch order at that point)

In [202]:
y[-1]

array([5.77700348])

In [176]:
outList= []
for k in range(7):
    for j in range(k):
        outList.append([ (bias[j]-bias[k])/(kern[0,k]-kern[0,j]), [k,j], np.argsort( [(bias[j]-bias[k])/(kern[0,k]-kern[0,j])] @ kern + bias ) ])
outList.sort()

In [177]:
outList

[[-14.617499999999696, [4, 0], array([3, 1, 5, 0, 4, 2, 6])],
 [-1.3854779743636036, [5, 1], array([3, 1, 5, 0, 4, 2, 6])],
 [0.17, [1, 0], array([3, 5, 0, 1, 4, 2, 6])],
 [0.6682944344703763, [4, 1], array([3, 5, 0, 4, 1, 2, 6])],
 [0.78, [2, 1], array([3, 5, 0, 4, 1, 2, 6])],
 [1.161717791411045, [4, 2], array([3, 5, 0, 2, 4, 1, 6])],
 [1.2166880433233576, [5, 0], array([3, 0, 5, 2, 4, 1, 6])],
 [1.8068455183631535, [5, 2], array([3, 0, 5, 2, 4, 1, 6])],
 [1.9110714285714288, [3, 0], array([3, 0, 2, 5, 4, 1, 6])],
 [2.0, [3, 2], array([0, 3, 2, 5, 4, 1, 6])],
 [2.057996863974912, [5, 3], array([0, 2, 5, 3, 4, 1, 6])],
 [2.0700000000000003, [4, 3], array([0, 2, 5, 4, 3, 1, 6])],
 [2.13, [5, 4], array([0, 2, 4, 5, 3, 1, 6])],
 [2.629677419354837, [3, 1], array([0, 2, 4, 5, 1, 3, 6])],
 [2.787307692307691, [6, 3], array([0, 2, 4, 5, 1, 3, 6])],
 [3.073730017761989, [6, 1], array([0, 2, 4, 5, 1, 6, 3])],
 [3.21512, [2, 0], array([0, 2, 4, 5, 6, 1, 3])],
 [4.999999999999999, [6, 5], array

In [191]:
mynet.model.predict(np.array([[1.5]]))

array([[1.85737705]])

In [200]:
mynet.model.save('sisotestmodel.h5')

## VolestiPy Example

This is a short example of how to use the VolestiPy library to generate samples from inside a polytope. NOTE: HPolytope is defined in terms of Ax <= b.

In [201]:
import volestipy

In [204]:
A = np.array( [[1,0], [-1,0], [0,1], [0,-1]] , dtype=np.float64)
b = np.array( [1, -2 , 0, -10] , dtype=np.float64)

In [207]:
poly = volestipy.HPolytope(-A,-b)

In [209]:
samples = poly.generate_samples(10)

In [211]:
samples[0:10]

array([[1.49994869, 7.92075959],
       [1.39978068, 0.3997041 ],
       [1.56513563, 7.82896172],
       [1.57821193, 8.174628  ],
       [1.23401778, 4.7823932 ],
       [1.29123014, 9.09923569],
       [1.08879678, 5.54214917],
       [1.54324589, 8.54456577],
       [1.05747004, 2.90304522],
       [1.95504744, 2.82493674]])

## Testing auto-generation of TLL networks

In [347]:
importlib.reload(TLLnet)

<module 'TLLnet.TLLnet' from '/Users/james/Dropbox/Research/Postdoc Yasser/code/TLLnet/TLLnet.py'>

### In 1-D

In [5]:
mytllnet = TLLnet.TLLnet(input_dim=1,output_dim=1,linear_fns=100,uo_regions=60)
mytllnet.generateRandomCPWA(scale=1)

/Users/james/Dropbox/Research/Postdoc Yasser/code/TLLnet/TLLnet.py:191: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  intersections[k], resid, rank, singVals = np.linalg.lstsq( \


In [8]:
mytllnet2 = TLLnet.TLLnet(input_dim=1,output_dim=1,linear_fns=100,uo_regions=60)
mytllnet2.generateRandomCPWA(scale=1)

/Users/james/Dropbox/Research/Postdoc Yasser/code/TLLnet/TLLnet.py:191: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  intersections[k], resid, rank, singVals = np.linalg.lstsq( \


In [6]:
x = np.linspace(-2,2,1000)
y = mytllnet.model.predict(x.reshape((len(x),1)))

In [7]:
fig = plt.figure(5)
fig.clf()
plt.plot(x,y)
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [370]:
mytllnet = TLLnet.TLLnet(input_dim=1,output_dim=1,linear_fns=63,uo_regions=100)
mytllnet.generateRandomCPWA(scale=1)
x = np.linspace(-2,2,1000)
y = mytllnet.model.predict(x.reshape((len(x),1)))
fig = plt.figure(7)
fig.clf()
plt.plot(x,y)
display(fig.canvas)

/Users/james/Dropbox/Research/Postdoc Yasser/code/TLLnet/TLLnet.py:191: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  intersections[k], resid, rank, singVals = np.linalg.lstsq( \


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### In 2-D

In [18]:
importlib.reload(TLLnet)
mytllnet = TLLnet.TLLnet(input_dim=2,output_dim=1,linear_fns=100,uo_regions=60)
mytllnet.generateRandomCPWA(scale=1)
x = np.linspace(-2,2,500)
X,Y = np.meshgrid(x,x)
xy = np.vstack([X.flatten(),Y.flatten()]).T
z = mytllnet.model.predict(xy)
Z = z.flatten().reshape((len(x),len(x)))
fig = plt.figure(10)
fig.clf()
ax = fig.add_subplot(111,projection='3d')
surf = ax.plot_surface(X, Y, Z, linewidth=2)
plt.show()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [371]:
importlib.reload(TLLnet)
mytllnet = TLLnet.TLLnet(input_dim=2,output_dim=1,linear_fns=128,uo_regions=150)
mytllnet.generateRandomCPWA(scale=1)
x = np.linspace(-2,2,750)
X,Y = np.meshgrid(x,x)
xy = np.vstack([X.flatten(),Y.flatten()]).T
z = mytllnet.model.predict(xy)
Z = z.flatten().reshape((len(x),len(x)))
fig = plt.figure(11)
fig.clf()
ax = fig.add_subplot(111,projection='3d')
surf = ax.plot_surface(X, Y, Z, linewidth=2)
plt.show()
display(fig.canvas)

/Users/james/Dropbox/Research/Postdoc Yasser/code/TLLnet/TLLnet.py:191: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  intersections[k], resid, rank, singVals = np.linalg.lstsq( \


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [171]:
with open('/Users/james/Dropbox/Research/Postdoc Yasser/NN Verification/TLLHyperCubeOutput/CDC2021/experiments/DUMMY_EXPERIMENT/TLLExperimentGroup20210225192514.p','rb') as fp:
    experimentGroup = pickle.load(fp)

In [72]:
import pickle
import volestipy

In [115]:
volPoly = volestipy.HPolytope(-1 * experimentGroup[0][0]['inputPoly']['A'], -experimentGroup[0][0]['inputPoly']['b'])

In [167]:
samps = volPoly.generate_samples(walk_len=500,n_samples=10000)

In [168]:
samps

array([[ 0.1910864 ],
       [-1.85544415],
       [ 0.54826784],
       ...,
       [-0.04386424],
       [ 0.32175534],
       [-0.65726419]])

In [172]:
fig = plt.figure(12)
plt.clf()
plt.plot(experimentGroup[0][0]['samples']['input'], experimentGroup[0][0]['samples']['output'],'.')
plt.show()
plt.axis([-2,2,-5,0])
plt.grid()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [174]:
experimentGroup[0][0]['inputPoly']

{'A': array([[ 1.        ],
        [-1.61774042]]),
 'b': array([-1.92489372, -1.        ]),
 'numFaces': 2,
 'polyDefinition': 'Ax >= b',
 'numGenerators': 10}

In [173]:
1/1.61774042

0.6181461423829665

In [170]:
np.maxif out >= self.m:
            raise ValueError('Output ' + str(out) + ' is greater than m = ' + str(self.m))(samps)

0.6178208620106906

In [80]:
newTLLnet = TLLnet.TLLnet(input_dim=1,output_dim=1,linear_fns=64,uo_regions=48)

In [81]:
for ii in range(len(experimentGroup[0][0]['TLLparameters']['selectorMatrices'][0])):
    newTLLnet.setSelector(experimentGroup[0][0]['TLLparameters']['selectorMatrices'][0][ii],ii)

In [82]:
newTLLnet.setLocalLinFns(experimentGroup[0][0]['TLLparameters']['localLinearFunctions'][0][0],experimentGroup[0][0]['TLLparameters']['localLinearFunctions'][0][1])

In [83]:
fig = plt.figure(15)
plt.clf()
x = np.linspace(-2,2,10000)
y = newTLLnet.model.predict(x.reshape((len(x),1)))
plt.plot(x, y,'.')
plt.show()
plt.axis([-2,2,-5,0])
plt.grid()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [145]:
y[175]

array([-4.08868524])

In [144]:
x[175]

-1.92999299929993

In [89]:
with open('/Users/james/Dropbox/Research/Postdoc Yasser/NN Verification/TLLHyperCubeOutput/CDC2021/experiments/DUMMY_EXPERIMENT/TLLExperimentGroup20210225192514.p','rb') as fp:
    experimentGroup = pickle.load(fp)

In [90]:
newTLLnet = TLLnet.TLLnet(input_dim=2,output_dim=1,linear_fns=64,uo_regions=48)

In [95]:
grp = 1
idxx = 0
for ii in range(len(experimentGroup[grp][idxx]['TLLparameters']['selectorMatrices'][0])):
    newTLLnet.setSelector(experimentGroup[grp][idxx]['TLLparameters']['selectorMatrices'][0][ii],ii)

In [96]:
newTLLnet.setLocalLinFns(experimentGroup[grp][idxx]['TLLparameters']['localLinearFunctions'][0][0],experimentGroup[grp][idxx]['TLLparameters']['localLinearFunctions'][0][1])

In [97]:
x = np.linspace(-2,2,750)
X,Y = np.meshgrid(x,x)
xy = np.vstack([X.flatten(),Y.flatten()]).T
z = newTLLnet.model.predict(xy)
Z = z.flatten().reshape((len(x),len(x)))
fig = plt.figure(11)
fig.clf()
ax = fig.add_subplot(111,projection='3d')
surf = ax.plot_surface(X, Y, Z, linewidth=2)
plt.show()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [77]:
fig = plt.figure(13)
fig.clf()
A = experimentGroup[grp][idxx]['inputPoly']['A']
b = experimentGroup[grp][idxx]['inputPoly']['b']
x = np.linspace(-2,2,1000)
for ii in range(len(A)):
    y = (1/A[ii,1]) * ( -A[ii,0]*x + b[ii] )
    plt.plot(x,y)
plt.axis([-2,2,-2,2])
plt.show()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [218]:
xy[np.argmax(z)]

array([0.47797063, 0.03471295])

In [228]:
np.min(z[validPts])

-3.551841951493664

In [225]:
validPts = list( map( lambda u: np.count_nonzero(A @ u - b >= 0) == len(A), xy )  )

In [226]:
[np.count_nonzero(validPts),len(xy)]

[182701, 562500]

In [216]:
experimentGroup[1][0]['inputPoly']['numFaces']

5

In [209]:
experimentGroup[1][0]['inputPoly']

{'A': array([[ 1.37273182, -1.        ],
        [ 1.01022848,  1.        ],
        [ 6.93162366, -1.        ],
        [-3.45676138,  3.72263055],
        [-1.        , -5.69430695]]),
 'b': array([ -3.6712379 ,  -3.49380178, -12.32920407,   1.        ,
        -10.05149732]),
 'numFaces': 5,
 'polyDefinition': 'Ax >= b',
 'numGenerators': 10}

In [ ]:
[array([1.63103849, 0.8667669 ]), array([2.39555668])]
[array([-1.2014224 ,  0.33283946]), array([-1.97864806])]
[array([0.40296976, 1.26905385]), array([0.34960276])]
[array([-0.30075663, -1.39122181]), array([-0.15542925])]

In [70]:
x = np.linspace(-2,2,1000)
fig = plt.figure(5)
fig.clf()
y1 = (-1.63103849*x - 2.39555668)/0.8667669
plt.plot(x,y1)
y2 = (1.2014224*x + 1.97864806)/0.33283946
plt.plot(x,y2)
y3 = (-0.40296976*x - 0.34960276)/1.26905385
plt.plot(x,y3)
y4 = (0.30075663*x + 0.15542925)/-1.39122181
plt.plot(x,y4)
plt.axis([-2,2,-2,2])
plt.grid()
plt.show()
display(fig.canvas)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [79]:
2**501

6546781215792283740026379393655198304433284092086129578966582736192267592809349109766540184651808314301773368255120142018434513091770786106657055178752